### ISSUE TITLE
I18N support to translate language strings

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_core#154]
To allow translation into multiple languages and customizations the Phovea platform needs an I18N integration. We decided that we will use [i18next](https://github.com/i18next).

**Comment by thinkh** [comment]
**Done so far**

* Created branch with initial implementation (see https://github.com/phovea/phovea_core/compare/thinkh/154_i18n-support and https://github.com/phovea/phovea_clue/compare/thinkh/154_i18n-support)
* Used phovea extension point mechanism to load locales
* Implemented `PhoveaBackend` as `i18next.BackendModule` to load locale files

**Challenges**

* Using a BackendModule (and the phovea extension points) makes the translate function `t()` async
* That would require that our apps have to wait until i18next is loaded, before initializing the app itself
* Overriding certain locales in other plugins (e.g., phovea_clue)

**Open questions / Next steps**

* Option 1: Can we use the i18next `t()` function sync and would it replace the language string after loading the locales? If this doesn't work we have to investigate option 2...
* Option 2: How could an app startup/loading look like if the app has to wait for i18next?
* Can certain language strings from locales be overriden in different plugins?

**Comment by oltionchampari** [comment]
Option 1: Can we use the i18next t() function sync and would it replace the language string after loading the locales? If this doesn't work we have to investigate option 2...

Answer:

- There is a way to use i18next.t() sync without restructuring the whole application, by setting `initImmediate: false `.

- That requires though for the resources to be loaded synchronously ,which means the  phovea extension point mechanism cannot be used since it returns a promise .

- This implementation would require that another way of loading/reading/overwriting the resources 

I any other case this applies : 
```
i18next.init();
i18next.t('key'); // outch not loaded

// 1sec later
i18next.t('key'); // yeah...works did load in the 1s

```
Source : https://github.com/i18next/i18next/issues/812
